driver:
  name: docker

platforms:
  - name: hv1
    image: geerlingguy/docker-debian12-ansible:latest
    privileged: true
  - name: hv2
    image: geerlingguy/docker-debian12-ansible:latest
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "${MOLECULE_PROJECT_DIRECTORY}/.."
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    hosts:
      all:
        children:
          hypervisors:
            hosts:
              hv1:
              hv2:
          cluster_machines:
            hosts:
              hv1:
              hv2:

verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    # - idempotence 
    # Disable idempotence test: wipe a directory and deploy a file in it, does not produce idempotent action.
    - verify
    - destroy
