# Copyright (C) 2024 RTE
# Copyright (C) 2024 Red Hat, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- import_tasks: vim.yml
- import_tasks: logging.yml
- import_tasks: users.yml
- import_tasks: sysctl.yml
- import_tasks: grub.yml
- import_tasks: network.yml
