---
- name: Converge
  hosts: all
  roles:
    - role: debian_hardening
  vars:
    revert: false
    admin_user: testadmin
    grub_password: "grub.pbkdf2.sha512.10000.DEADBEEF"
    ip_addr: "192.168.1.10"
  pre_tasks:
    - name: Create test admin user
      ansible.builtin.user:
        name: testadmin
        state: present
